all: ball.cpp board.cpp 
	g++ ball.cpp board.cpp 
	
# compress: hashing.cpp HashTable.cpp WordCompression.cpp WordDecompression.cpp Compression.cpp
# 	g++ hashing.cpp HashTable.cpp WordCompression.cpp WordDecompression.cpp Compression.cpp

# decompress:
# 	g++ WordDecompression.cpp Decompression.cpp

clean:
	rm a.out

